
Meta:
  file: 'nn_256_wpoly'


Model:
  NeuralNet:
    ensemble: [
                'FBL_L1', 'FBL_L2', 'FBL_Sc', 'FBL_LDA', 'FBL_LDA_L1', 
                'FBLCA_L1', 'FBLCA_L2', 'FBLCA_Sc', 'FBLCA_LDA', 'FBLCA_LDA_L1',
                'FBL_delay_L1', 'FBL_delay_L2', 'FBL_delay_Sc', 'FBL_delay_LDA',
                
                'C500_[1_15]_LR', 
                'C500_[7_30]_LR', 
                'C500_[20_35]_LR', 
                # # 'C500_[70_150]_LR', 
                'C250_[35]_LR', 
                'C500_[35]_LR', 
                'ERPDist', 
                'CAll_old_LR',
                
                'C500_[1_15]_poly_LR',
                'C500_[7_30]_poly_LR',
                'C500_[20_35]_poly_LR',
                # 'C500_[70_150]_poly_LR',
                'C250_[35]_poly_LR',
                'C500_[35]_poly_LR',
                'ERPDist_poly',
                
                # 'CNN_1D_FB30',
                # 'CNN_2D_FB30', 
                # 'CNN_1D_FB7-30',
                # 'CNN_1D_FB5',
                
                'RNN_FB_delay4000',
                
                ]
    training_params:
      lr: 0.1
    
    delay: 256
    skip: 18
    partsTrain: 2
    partsTest: 2
    smallEpochs: 2
    majorEpochs: 20
    checkEveryEpochs: 5

    architecture:
      - 'Dropout':
            p: 0.5
      - 'Dense':
            num_units: 256
      - 'Activation':
            type: 'relu'
      - 'Dropout':
            p: 0.7
      - 'Output':
