imports:
    preprocessing.filterBank:
        - FilterBank
    preprocessing.aux:
        - IdenticalTransformer
    sklearn.preprocessing:
        - StandardScaler
        - Normalizer

Meta:
  file: 'NN_256'
  cachePreprocessed: False

Preprocessing:
  - FilterBank:
      filters: [[1],[5],[10],[30]]
    # - StandardScaler:
    # - Normalizer:

Training:
  lr: 0.1
  decay: 1e-6
  momentum: 0.9
  delay: 256
  skip: 1
  parts_train: 2
  parts_test: 1
  smallEpochs: 2
  majorEpochs: 10
  checkEveryEpochs: 2
  subsample: 1

Architecture:
    - 'Dropout':
        p: 0.5
    - 'Dense':
        num_units: 256
    - 'Activation':
        type: 'tanh'
    - 'Dropout':
        p: 0.7
    - 'Output':
    - 'Activation':
        type: 'tanh'

        
